name: shopping_app
description: Lista de compras con autenticación y API.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado
  provider: ^6.0.6

  # Almacenamiento seguro de token
  flutter_secure_storage: ^8.0.0

  # Peticiones HTTP
  http: ^1.2.3

  # Utilidades y compatibilidad
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5

  # Fuentes personalizadas
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

